[package]
name = "pyrgo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "pyrgo"
crate-type = ["cdylib"]

[dependencies]
clap = "4.2.7"
pyo3 = "0.18.3"
toml = "0.7.3"
